import { defineConfig, type OpenApiInfoObject } from "orval"

const SPEC_PATH = "../api/openapi.json"

const header = ({ title, description, version }: OpenApiInfoObject = {}) => [
  "Generated by orval 🍺",
  "Do not edit manually.",
  ...(title ? [title] : []),
  ...(description ? [description] : []),
  ...(version ? [`OpenAPI spec version: ${version}`] : []),
]

export default defineConfig({
  honoPocApi: {
    input: { target: SPEC_PATH },
    output: {
      mode: "tags-split",
      client: "react-query",
      httpClient: "fetch",
      target: "src/shared/api/generated/endpoints",
      schemas: "src/shared/api/generated/models",
      mock: { generators: [{ type: "msw", delay: false }] },
      override: {
        header,
        mutator: {
          path: "./src/shared/api/fetch-mutator.ts",
          name: "customFetch",
        },
        query: { useSuspenseQuery: true },
        fetch: { includeHttpResponseReturnType: false },
      },
    },
  },
  honoPocApiZod: {
    input: { target: SPEC_PATH },
    output: {
      mode: "tags-split",
      client: "zod",
      target: "src/shared/api/generated/endpoints",
      fileExtension: ".zod.ts",
      override: { header },
    },
  },
})
