dsn: ${DATABASE_URL}
docPath: docs/db
exclude:
  - drizzle.*
er:
  skip: true
lint:
  requireTableComment:
    enabled: true
  requireColumnComment:
    enabled: true

comments:
  - table: authors
    tableComment: 著者
    columnComments:
      id: 著者ID
      name: 名前
      version: バージョン
      created_at: 作成日時
      updated_at: 更新日時
  - table: books
    tableComment: 書籍
    columnComments:
      id: 書籍ID
      title: タイトル
      version: バージョン
      created_at: 作成日時
      updated_at: 更新日時
  - table: book_authors
    tableComment: 書籍と著者の関連
    columnComments:
      book_id: 書籍ID
      author_id: 著者ID
