name: tbls

on:
  pull_request:
    types: [opened, reopened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  tbls:
    name: tbls
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/app?sslmode=disable
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup
        with:
          mise-install-args: node pnpm tbls
      - uses: ./.github/actions/database
      - name: Run tbls lint
        run: tbls lint
